// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pkiocjemdqrmkrsuhcoy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBraW9jamVtZHFybWtyc3VoY295Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3ODc1MTcsImV4cCI6MjA2NjM2MzUxN30.s7q7uSvqDvLbf31uRkocbTyEYV0MFf59MJ4npwD2a1k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);